### ISSUE TITLE
AstroSeo position

### ISSUE THREAD

**Issue by zanhk** [onwidget/astrolib#12]
From the documentation (https://github.com/onwidget/astrolib/tree/main/packages/seo) it's not clear if I have to put the tag inside the `head`  or I can place anywhere in the page and it will add the tags automatically to the head.

Because from the docs seem like it's the second case

> Then you need to import @astrolib/seo and add the desired properties. This will render out the tags in the <head> for SEO.

but this case doesn't seem to be working as it place the tags before the root html tag

![image](https://github.com/onwidget/astrolib/assets/17980844/88851010-3945-4d5d-a6ff-bb26960a639a)

https://validator.w3.org/nu/?showsource=yes&showoutline=yes&doc=https%3A%2F%2Fmajestico.it%2F

Is it supposed to be placed inside the head tag?

Thanks

**Comment by TheElegantCoding** [comment]
Looking the source code you can see this is inside the head because the SEO component return the html tags

**Comment by zanhk** [comment]
Yeah I saw, it's just not clear from the docs, but  this repo doesn't seem to be maintened anymore
