### ISSUE TITLE
Add support for additional twitter tags like title and description

### ISSUE THREAD

**Issue by jceb** [onwidget/astrolib#8]
See https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup

**Comment by ttmc** [comment]
As noted on that page you linked-to, if the `twitter:title` tag is not present, then Twitter/X will fall back to the `og:title` tag, if present. Likewise for `twitter:description` and `og:description`.

That said, careful study of the linked page reveals that there are *other* twitter tags that don't have any og fallback, yet they're not supported by this package...

**Comment by jceb** [comment]
Ah, that's good to know. I didn't realize that the OpenGraph column points to the fallback value.
